---
- name: crete remote directory and copy the file
  hosts: webserver
  become: true
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.facts    
    web_pkg: apache2 
  tasks:
    - name: install apache
      apt:
        name: "{{ web_pkg }}"
        state: latest
        update_cache: yes
    - name: create a remote directory
      file:
        path: "{{ remote_dir  }}"
        state: directory
    - name: copy the file
      copy:
        src: "{{ facts_file  }}"
        dest: "{{ remote_dir }}" 
    - name: print the out of ansible facts
      debug:
        msg: > 
                The distribution is {{ ansible_distribution }}version is {{ ansible_distribution_major_version}} and ip address is {{ansible_all_ipv4_addresses}}