---
- name: crete remote directory and copy the file
  hosts: webserver
  become: true
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.facts     
  tasks:
    - name: install apache
      apt:
        name: apache2
        state: latest
        update_cache: yes
    - name: create a remote directory
      file:
        path: "{{ remote_dir  }}"
        state: directory
    - name: copy the file
      copy:
        src: "{{ facts_file  }}"
        dest: "{{ remote_dir }}"