---
# tasks file for block
- block:
  - name: install apache
    apt:
      name: apache2
      state: latest
  - name: create directory name as kyndryl
    file:
      path: "{{ directory_path }}"
      state: directory

  - name: give the  permission for directory
    file:
      #group: root
      group: ansible
      path: "{{ permission_dir_path}}"
      mode: 0755
    tags: kyndryl
  - name: create the file named as hello
    file:
      #group: root
      group: ansible
      path: "{{ file_path }}"
      state: touch
      #mode: 0644
      mode: u=rw,g=r,o=r
    tags: hello
  - name: for hello file give add/remove permissions"
    file:
      path: "{{ file_path }}"
      state: touch
      mode: u+rwx,g+rw,o-rwx
  - name: print the above information
    debug:
      msg: "Directory and File created and given the permissions"
    notify:
      - restart apache2
