---
# tasks file for update_repos
   - name: install apache
     apt:
       name: "{{ web_pkg }}"
       state: latest
       update_cache: yes
   - name: create a remote directory
     file:
       path: "{{ remote_dir  }}"
       state: directory
   - name: copy the file
     copy:
       src: "{{ facts_file  }}"
       dest: "{{ remote_dir }}" 
   - name: print the output of ansible facts
     debug:
       msg: "Tasks successfully run by using roles"
               #The distribution is {{ ansible_distribution }} 
               #version is {{ ansible_distribution_major_version}} and 
               #ip address is {{ansible_all_ipv4_addresses}}
               # os family is  {{ansible_os_family}} and ansible bios date {{ansible_bios_date}}
